### ISSUE TITLE
Theme Application detail page

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#10]
Paul, the Application content type for the Apps Catalog distro has been built with different field names than the field names that were used for the Civic Commons Marketplace and Sanitation Hackathon website, but it should be themed to look very similar to those pages. There will be some colored header blocks and content in the main content area, and the right sidebar will hae an "At a glance" block similar to what you see here:

http://www.sanitationhackathon.org/applications/frontlinesms
http://commons.codeforamerica.org/apps/drupal

We need to theme the Apps Catalog distro so that applications such as this one look similar to that:

http://apps-cat.nuamsdev.com/content/drupal 

I've created a Google doc with a section on theming that shows where each field in the Appliction content type should go:

https://docs.google.com/a/nuams.co/document/d/1evXooY8fGT9PYia600bBPFOW6DW1PqjzNZlYvdAFas4/edit#

Let's discuss this with Federica so that you and she can work out any details about how to implement this.

**Comment by fusionx1** [comment]
for review

**Comment by acouch** [comment]
Paul, please see my comments.

**Comment by sheldonrampton** [comment]
Aaron, where are your comments on this?

**Comment by acouch** [comment]
They were in the commit. Paul corrected me about the formatting.
