### ISSUE TITLE
Deployment organisations not clear

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#100]
A page like http://demo.opencivic.nuamsdev.com/deploy/deployment-drupal shows a list of orgs that were "developers". Should these be separated into developers and "clients"?

Equally this page http://demo.opencivic.nuamsdev.com/orgs also shows all the organizations mixed up. Also worth separating?

**Comment by sheldonrampton** [comment]
I'll review and comment on this.

**Comment by sheldonrampton** [comment]
I've changed the label for the "Developers" field to "Related Organizations."

**Comment by pmackay** [comment]
I'm still seeing the "Developers" label on the 7.x branch - could you recheck this? Which commit was it?

**Comment by pmackay** [comment]
Think this is resolved now.
