### ISSUE TITLE
Make hackathon theme regions consistent with cat_lover regions

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#106]
assumption: use "first" and "second" rather than "left" and "right" when naming regions and zones.
create a list of common base themes and the names of their common regions as a guide

**Comment by sheldonrampton** [comment]
Paul, please confirm that this ticket can be closed and, if so, close it. It should now be possible to switch between the Cat Man Do and Cat Lover themes, with both working more or less as expected. Additionally, it should be possible to use other AdaptiveTheme subthemes fairly easily.

This Google doc details the changes that I made to the Cat Lover theme:

https://docs.google.com/a/nuams.co/document/d/1YGwsoithBxDA6mMuIyN1lDlmKr_iC7Yj97LGT004PKU/edit#heading=h.43o2rx7krjw4

**Comment by pmackay** [comment]
Both themes are showing most basic regions well enough to be switchable easily. Closing.
