### ISSUE TITLE
Multilingual breaks default content

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#109]
Upon merging in the latest multilangual functionality, there are some issues with default content not being created properly. Specifically, application node descriptions and civic sector taxonomy terms are not created properly during initial site setup. Also, image fields for taxonomy terms are not created properly.

Additional problems occur if the multilingual functionality is not enabled prior to performing the "Applications Catalog default content" step in the setup script.

Since these problems only affect the default content, this is not a blocker to being abe to create websites with OpenCivic, but it should be corrected.

**Comment by pmackay** [comment]
Default content removed (partly cos of this issue) so closing.
