### ISSUE TITLE
Merge in At a Glance label changes

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#118]
Hi Sheldon,

Did you merge into OC the changes I made to the At a Glance view on the app details page? I removed some colons and made all the labels lower case. Also did some tweaks to similar views for Orgs, etc.

It was this commit:

https://github.com/civic-commons/opencivic/commit/0283dfec9f8b8627e6fb9131827f1d0845344080

**Comment by pmackay** [comment]
This is now resolved.
