### ISSUE TITLE
Drush makefile for -dev versions of modules

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#15]
Aaron, I'd like your advice regarding how to create the Drush makefile for modules where I need to be using a dev version of the module. Currently the makefile contains 11 dev modules.

The general advice I've read with respect to creating installation profiles is that the makefile should specify a specific release version of each module to minimize the risk that changes in one module will break something. However, the 11 dev modules in the apps catalog are currently an exception to this rule, since by definition the dev version is a development snapshot that can change whenever the developer pushes a new commit.

As an example, I'm currently using the UUID Features module, and the module's project page explains that for it to work properly with the UUID module, I need to be using the current dev release of UUID Features. In addition, I've patched UUID Features so it can support exporting taxonomy file fields. The Drush makefile lines for UUID Features are therefore as follows:

projects[uuid_features][version] = "1.x-dev"
projects[uuid_features][subdir] = "devel"
; Patch UUID Features module to support exporting taxonomy file fields
; http://drupal.org/node/1893914
projects[uuid_features][patch][1893914] = http://drupal.org/files/taxonomy_field_fields-1893914-1.patch

This creates a problem for the stability of the Drush makefile. If the UUID Features project maintainer pushes a new commit that prevents my patch from applying, Drush make will fail.

To avoid this risk, I could change the Drush makefile for this module to something like the following which would retrieve a specific git commit of the module:

projects[uuid_features][download][type] = "git"
projects[uuid_features][download][url] = "git://drupalcode.org/project/uuid_features.git"
projects[uuid_features][download][revision] = "924559bcf71e39c15374fb2b9623df16075f3ccf"

I'm wondering if we should do this for all dev modules in the project and would appreciate your advice.

**Comment by acouch** [comment]
I think this is a good idea. Though during development I think we should try and keep up to date with upstream changes as much as possible. If it breaks now it is better then not being able to use the next stable release. I would use dev versions until an arbitrary time in the project when we want the distro itself to be stable then switch to specific commits.

**Comment by sheldonrampton** [comment]
My question is more specific. For most of the contrib modules in the distro, my makefile designates a specific release version of that module. However, there are 11 or 12 modules for which I have no choice but to use the latest dev version. For example, the UUID Features module _requires_ that I used the dev version of the UUID module.
