### ISSUE TITLE
Wrong version of Drupal core

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#16]
When Jenkins reinstantiates the Apps Catalog distro, it imports Drupal 7.18 rather than 7.19, even though I've updated file distro.make to specify D7.19, which is in fact the Drupal version that I see specified at http://apps-cat.nuamsdev.com/profiles/apps_catalog/distro.make

Can you fix this?

**Comment by acouch** [comment]
I fixed this.
