### ISSUE TITLE
App Page · remove "logo" title bar

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#17]
In the App page remove the green bar and the "logo" title, aswell as the "basic info" title.

![capture](https://f.cloud.github.com/assets/1379537/85669/69bb50d0-6471-11e2-856c-44f1424c6a7e.png)

**Comment by sheldonrampton** [comment]
Paul, I'm assigning this to you.

**Comment by fusionx1** [comment]
this is done.

**Comment by sheldonrampton** [comment]
Please push your code so I can review it.

**Comment by acouch** [comment]
Paul, if you pushed a commit in relation to this ticket, you didn't add the ticket # in the commit message. Can you link to the commit?

**Comment by acouch** [comment]
Looks great!

**Comment by sheldonrampton** [comment]
Confirmed and closing.
