### ISSUE TITLE
App Page · If there's no video, don't show "video" title bar

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#19]
If the app doesn't have a video file or embed, don't render the title bar "video"

![Screen Shot 2013-01-22 at 17 06 52](https://f.cloud.github.com/assets/1379537/85691/1de36af6-6473-11e2-82e4-e98ba4265325.png)

**Comment by sheldonrampton** [comment]
Paul, this should show images of both video and screenshots with no title bar above it, similar to the way screenshots and videos display on the Civic Commons website. For example, look at this page on the Civic Commons site:

http://commons.codeforamerica.org/apps/waste-nothing

**Comment by fusionx1** [comment]
this has been fixed in my local but when my macbook's battery broke down i wasnt able to push my changes

**Comment by sheldonrampton** [comment]
Paul, can you fix this now?
