### ISSUE TITLE
Call to action buttons CSS

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#21]
![Screen Shot 2013-01-22 at 17 20 17](https://f.cloud.github.com/assets/1379537/85714/1093f33c-6475-11e2-8322-1597964793e2.png)

styles:

`<style type="text/css">
.button {
    -moz-box-shadow:inset 0px 1px 0px 0px #91a6d6;
    -webkit-box-shadow:inset 0px 1px 0px 0px #91a6d6;
    box-shadow:inset 0px 1px 0px 0px #91a6d6;
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #6280cb), color-stop(1, #102047) );
    background:-moz-linear-gradient( center top, #6280cb 5%, #102047 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#6280cb', endColorstr='#102047');
    background-color:#6280cb;
    -moz-border-radius:3px;
    -webkit-border-radius:3px;
    border-radius:3px;
    border:1px solid #142859;
    display:inline-block;
    color:#ffffff;
    font-family:arial;
    font-size:15px;
    font-weight:bold;
    padding:11px 28px;
    text-decoration:none;
    text-shadow:1px 1px 0px #101f42;
}.button:hover {
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #102047), color-stop(1, #6280cb) );
    background:-moz-linear-gradient( center top, #102047 5%, #6280cb 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#102047', endColorstr='#6280cb');
    background-color:#102047;
}.button:active {
    position:relative;
    top:1px;
}
</style>`

**Comment by sheldonrampton** [comment]
Paul, assigning this to you.

**Comment by acouch** [comment]
This seems like something we should turn into a mixin. I am just flagging it for now and will add code if I have time.

**Comment by fusionx1** [comment]
the .button style has been added in the stylesheet

**Comment by sheldonrampton** [comment]
Confirmed and closing.
