### ISSUE TITLE
App Page · Fix padding in "categories" and "civic categories"

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#22]
There's currently too much space between each category and civic category. reduce by 5 to 7px.

![Screen Shot 2013-01-22 at 17 26 23](https://f.cloud.github.com/assets/1379537/85739/79b36b1c-6476-11e2-98fd-5b1c9915ab82.png)

**Comment by fusionx1** [comment]
padding adjusted

**Comment by sheldonrampton** [comment]
Federica, can you review this and see if it looks right to you now?
