### ISSUE TITLE
App Page · Add separators between sidebar items

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#23]
In the App Page sidebar, add a separating line (and a few pixels margin) in between items, like so

![Screen Shot 2013-01-22 at 17 55 52](https://f.cloud.github.com/assets/1379537/85846/1d721542-647b-11e2-808f-bc5aca7586be.png)

**Comment by sheldonrampton** [comment]
Paul, assigning this to you.

**Comment by fusionx1** [comment]
this has been fixed on my local, will push my changes tomorrow as soon as i have the laptop from mark caballero

**Comment by sheldonrampton** [comment]
Paul, this ticket specifies that you should add a separating line between items. The CSS that you pushed doesn't add a separating line or any space between items.

**Comment by fusionx1** [comment]
the separation line is now showing

**Comment by pmackay** [comment]
Reviewed.
