### ISSUE TITLE
Create organization content type

### ISSUE THREAD

**Issue by NewAmsterdamIdeas** [civic-commons/opencivic#3]
Aaron, can you create the organization content type and export it as a feature? Here's a screenshot:

![ticketpage](https://f.cloud.github.com/assets/345055/48614/6fb6dd3a-5916-11e2-9c4e-539d0212d2f7.png)

**Comment by acouch** [comment]
I don't feel like doing this. 
![images](https://f.cloud.github.com/assets/512243/48620/ed1560bc-5916-11e2-8e9d-d8d8b3d884b6.jpeg)

**Comment by NewAmsterdamIdeas** [comment]
OK, I'm closing this ticket because Aaron is being so grumpy.
