### ISSUE TITLE
Incorporate design ideas from MobileDevelopmentIntelligence

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#34]
https://mobiledevelopmentintelligence.com/products

**Comment by acouch** [comment]
Let me know if you need help with this.

**Comment by pmackay** [comment]
Can the description of this be expanded to describe what design ideas are being considered from that site?

**Comment by sheldonrampton** [comment]
I just wanted to review it for a few ideas about what fields to expose in the views form filters.
