### ISSUE TITLE
App Page · fix logo resize and cropping

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#42]
Currently the logo image is being cropped incorrectly. 

![Screen Shot 2013-01-31 at 18 59 59](https://f.cloud.github.com/assets/1379537/114422/dc41b97c-6b9d-11e2-994b-4db760bd9ad4.png)

**Comment by sheldonrampton** [comment]
Paul, please change this so it scales but doesn't scale and crop.

**Comment by sheldonrampton** [comment]
Approved and closing.
