### ISSUE TITLE
App Page · Category Styles

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#43]
On the sidebar Category items with an icon, align vertically icon and title.
remove the underlined text style from category links.

![Screen Shot 2013-01-31 at 19 01 19](https://f.cloud.github.com/assets/1379537/114428/4f3b04e2-6b9e-11e2-989f-5a381e2c9bc9.png)

**Comment by sheldonrampton** [comment]
Paul, are you working on this?

**Comment by fusionx1** [comment]
this is now fixed

**Comment by pmackay** [comment]
Reviewed.
