### ISSUE TITLE
App Page · remove unnecessary links

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#44]
Remove the following links:

Under Key Features: Photos and Videos, Screenshots
Under Screenshots: Tutorials

![Screen Shot 2013-01-31 at 19 06 13](https://f.cloud.github.com/assets/1379537/114429/a614c42e-6b9e-11e2-8b92-305dcae5fe9d.png)

**Comment by sheldonrampton** [comment]
Approved and closing.
