### ISSUE TITLE
App Page · User Login block width

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#45]
On the sidebar the user login block has a smaller width than it should. Please make it the same width as all the other sidebar blocks

![Screen Shot 2013-01-31 at 19 07 21](https://f.cloud.github.com/assets/1379537/114432/e3c8e07a-6b9e-11e2-8fec-3418cb0acb59.png)

**Comment by sheldonrampton** [comment]
It looks like this is fixed, so closing.
