### ISSUE TITLE
App Page · change <p> font in description to Helvetica

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#46]
Currently the description font is PT Sans while the rest of the page is Helvetica/arial/sans-serif. Please change and unify.

![Screen Shot 2013-01-31 at 18 59 59](https://f.cloud.github.com/assets/1379537/114441/31689ea6-6b9f-11e2-99ff-44def00d9da5.png)

**Comment by sheldonrampton** [comment]
Paul, are you working on this?

**Comment by fusionx1** [comment]
this is now fixed, but the images should be reuploaded, because the image cache will only work as after the features are fully enabled

**Comment by pmackay** [comment]
Reviewed.
