### ISSUE TITLE
App Page · Unify Title Bar fonts

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#47]
Fonts for the Title Bar titles are different in the central column and sidebar. Please unify to Helvetica/Arial/Sans-serif

![Screen Shot 2013-01-31 at 19 12 39](https://f.cloud.github.com/assets/1379537/114446/b2273610-6b9f-11e2-9c6d-bb2f9cb9e2f2.png)

**Comment by sheldonrampton** [comment]
The character spacing in title bars looks a little weird to me. Federica, does it look OK to you?

**Comment by pmackay** [comment]
Reviewed.
