### ISSUE TITLE
App Page · Change hover color for all <a>

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#48]
Change hover color for all <a> elements from red to #7793ec

**Comment by sheldonrampton** [comment]
Paul, the category links in the right sidebar aren't changing to the hover color when I mouse over them. See the attached screenshot.

![hoverlinks](https://f.cloud.github.com/assets/2838758/168481/86dc68f6-79fd-11e2-8694-84b99383cfbc.png)

**Comment by pmackay** [comment]
Reviewed. Looks resolved.
