### ISSUE TITLE
Search errors

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#52]
I've encountered some errors with the search feature that you created. The errors are happening both on a test instance that I spun up on my laptop as well as on apps-cat.nuamsdev.com

**First, the Drupal installation produces a number of error messages that look like this:**

Notice: Undefined index: field_additional_type in SearchApiDbService->indexItem() (line 332 of /Users/sheldonrampton/Sites/worldbank/appcat/our_distro/full_code/profiles/apps_catalog/modules/contrib/search_api_db/service.inc).
Notice: Undefined index: field_additional_type in SearchApiDbService->indexItem() (line 333 of /Users/sheldonrampton/Sites/worldbank/appcat/our_distro/full_code/profiles/apps_catalog/modules/contrib/search_api_db/service.inc).

**Second, when I try to search for a search term such as "drupal" I get "no results found."**

**Third, errors are produced when I go to http://apps-cat.nuamsdev.com/admin/config/search/search_api/index/apps_cat_db_nodes_index/status and try to manually index the site.**

I see a bunch of messages in the error log like this one at http://apps-cat.nuamsdev.com/admin/reports/event/4357 :

TYPE    search_api_db
DATE    Thursday, February 7, 2013 - 03:53
USER    admin
LOCATION    http://apps-cat.nuamsdev.com/batch?id=13&op=do
REFERRER    http://apps-cat.nuamsdev.com/batch?op=start&id=13
MESSAGE SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apps_cat_live.search_api_db_apps_cat_db_nodes_index_search_api_language' doesn't exist
SEVERITY    warning
HOSTNAME    75.135.78.65

**Comment by acouch** [comment]
This should be a release blocker: http://drupal.org/node/1347438#comment-7038870

Basically reverting a feature with search_api_db in it breaks search.

I'm doing a fix for our release process but this is an issue we need to follow.
