### ISSUE TITLE
Eliminate "subcategory" taxonomies and use hierarchical taxonomies instead

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#56]
Instead of "application category" and "application subcategory," we should use a single, two-level taxonomy named "app function."

Instead of "civic category" and "civic subcategory," we should use a single, two-level taxonomy named "civic sector."

**Comment by sheldonrampton** [comment]
Aaron, I'm assigning this to you for code review.

**Comment by acouch** [comment]
Looks good!

**Comment by pmackay** [comment]
Would it be clearer to merge "Deployment and support" and "Categories" as tabs?

**Comment by pmackay** [comment]
Reviewed.
