### ISSUE TITLE
Demo site not being built correctly

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#6]
Aaron, the Apps Catalog website is still not getting built correctly. Here's what it looks like now:

http://apps-cat.nuamsdev.com/

All it gives me is "permission denied," and it won't recognize the username and password when I try to log in.

I did a test install of the distro on my laptop and it installed correctly (although it took quite awhile to complete).

**Comment by acouch** [comment]
When I try and install locally I get the following:

`
WD php: PDOException: SQLSTATE[HY000]: General error: 29 File '/var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/regions.csv' not found (Errcode: 13): LOAD   [error]
DATA INFILE '/var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/regions.csv' REPLACE INTO TABLE addressfield_extras_region FIELDS TERMINATED BY ',' OPTIONALLY
ENCLOSED BY '"' LINES TERMINATED BY '
' (iso, fip, name); Array
(
)
 in addressfield_extras_install() (line 45 of /var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/addressfield_extras.install).
Cannot modify header information - headers already sent by (output started at /usr/local/lib/drush/includes/output.inc:37) bootstrap.inc:1212                                                  [warning]
PDOException: SQLSTATE[HY000]: General error: 29 File &#039;/var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/regions.csv&#039; not found (Errcode: 13): LOAD DATA INFILE &#039;/var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/regions.csv&#039; REPLACE INTO TABLE addressfield_extras_region FIELDS TERMINATED BY &#039;,&#039; OPTIONALLY ENCLOSED BY &#039;"&#039; LINES TERMINATED BY &#039;
&#039; (iso, fip, name); Array
(
)
 in addressfield_extras_install() (line 45 of /var/www/apps_cat/webroot/profiles/apps_catalog/modules/custom/addressfield_extras/addressfield_extras.install).
`

**Comment by acouch** [comment]
Looks like this worked: http://apps-cat.nuamsdev.com/

Just after I finished this I found that the Smart IP module has a lookup function for what it looks like you were using: http://drupalcode.org/project/smart_ip.git/blob/refs/heads/7.x-1.x:/includes/smart_ip.region_lookup.inc

**Comment by acouch** [comment]
I'm not sure this works properly with drush_cron. Will take another look when I get a chance.

**Comment by sheldonrampton** [comment]
Fixed and closing.
