### ISSUE TITLE
uuid_node breaking build

### ISSUE THREAD

**Issue by acouch** [civic-commons/opencivic#65]
I'm getting the following error when installing the site using drush:

WD node: PDOException: SQLSTATE[23000]: Integrity constraint             [error]
violation: 1062 Duplicate entry '' for key 'uri': INSERT INTO
{file_managed} (filesize, status, timestamp, type, uuid) VALUES
(:db_insert_placeholder_0, :db_insert_placeholder_1,
:db_insert_placeholder_2, :db_insert_placeholder_3,
:db_insert_placeholder_4); Array
(
    [:db_insert_placeholder_0] => 0
    [:db_insert_placeholder_1] => 1
    [:db_insert_placeholder_2] => 1360795975
    [:db_insert_placeholder_3] => default
    [:db_insert_placeholder_4] =>
3aca55d6-8e27-4ccf-8829-392f7fa1f37e
)

I've seen issues with a similar error that say it is a file permissions issue, but I've tried giving the files folder full open permissions to no avail.

**Comment by acouch** [comment]
http://drupal.org/node/1102308#comment-5033516

**Comment by pmackay** [comment]
Is this still a problem? I've not seen it. What drush steps create this error?
