### ISSUE TITLE
Implement faceted search for key parameters

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#69]
This depends on the taxonomies but could provide facets for:
- type of deployment organisation
- project license
- status? (in development, maintained, etc)
- geographic region
- technologies (languages, frameworks)
- platform (web app, native app, server tech)
- supported languages

**Comment by a-campbell** [comment]
This would be incredibly helpful to me...

**Comment by pmackay** [comment]
@theandycamps - improvements are being developed on a 2.x branch but all issue activity is happening here https://drupal.org/project/opencivic. This project is not being updated.
