### ISSUE TITLE
Site building procedures documentation

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#7]
Paul, I've written a couple of documents describing procedures that we should be following when we build websites and Drupal distros. Please read both of these documents.

Nuams naming policy for custom modules, features, contexts and views:

https://docs.google.com/a/nuams.co/document/d/1gBMvrZ5Jmh5fv8A7T8LjV9i8Ki_cP7slrkkQFxIP08g/edit#heading=h.ersfvhe52mfx

Using Git to build Drupal distros

https://docs.google.com/a/nuams.co/document/d/1Eucocy6HCeBKzNpxu7cYvlazqi_wUcc7TnRSpOaaF58/edit#heading=h.5k0ozwxnd82h

**Comment by fusionx1** [comment]
done reviewing the documents
