### ISSUE TITLE
Can Libraries module be updated to v2?

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#77]
To provide an API the Services module is needed. Services 7.x-3.3 requires a version of Libraries >2.0. If we upgrade Libraries will this affect any other components?

**Comment by pmackay** [comment]
In what way does the distro currently use the OpenLayers Feature Popups module (http://drupal.org/project/olfp). This seems to be the only enabled module with a dependency on Libraries. Updating to the latest version of Libraries and running update does not seem to have any negative effects.

**Comment by sheldonrampton** [comment]
I've updated to Libraries 2.0 and have also removed the OLFP module. The OLFP module was an attempt to resolve a bug in the version of OpenLayers that I was using. I was able to resolve that bug by updating to the current dev version of Open Layers 7.x-2.x, so I don't need the OLFP module after all.
