### ISSUE TITLE
Demo site and taxonomies documentation

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#8]
Samhir, I have running demo instance of the Apps Catalog that you can review at:

http://apps-cat.nuamsdev.com/

I've sent you a separate email with the username and password to log into the demo instance.

Please note that the demo instance of the Apps Catalog may become temporarily unavailable from time to time whenever we push changes to the codebase. Also, the demo doesn't currently look like much. (But it will start coming into focus soon.)
## Documentation

I have created a document listing all taxonomies and taxonomy terms, which you can review here:

https://docs.google.com/a/nuams.co/document/d/1spokprX0aM_fuKp7uo9QEfWorjX9m1kAzLdT-C5S8EA/edit#

Please feel free to add notes to the document listing any revisions that you think are needed.

FYI, if you are logged into the demo instance of the website, you can also review the list of taxonomies directly on the website itself at:

http://apps-cat.nuamsdev.com/admin/reports/architecture/taxonomies

The version that you see directly on the website will be current as of the latest code commit. The Google doc may be less up-do-date but will let you add comments (which the you can't do on the demo website).

Also please note that I've started a wiki page here on GitHub with references to site information and documentation including the information in this ticket:

https://github.com/nuams/apps_catalog/wiki

**Comment by svasdev** [comment]
Thanks. I was able to log in no problem, but taxonomies URL took me to the attached page and I wasn't sure where to go from there.

The actual demo worked fine, although I didn't see much to work with (no content types, etc.) - assume more is coming.

On the taxonomies GoogDoc, I continue to review and will make comments when applicable.

![Reports Apps Catalog](https://f.cloud.github.com/assets/1396543/78739/31d05a22-6191-11e2-9e35-7621ab141e37.png)

**Comment by svasdev** [comment]
Sheldon, I've gone through the taxonomies doc and made some comments for which your input would be valuable. Reassigning to you.
