### ISSUE TITLE
Investigate including patch so schema.org mappings are auto-included in Features export

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#88]
See http://drupal.org/node/1853590 .

**Comment by sheldonrampton** [comment]
This patch applies cleanly, so I'm going ahead and adding it to the distro.

**Comment by sheldonrampton** [comment]
The patch has been added. We still need to confirm that feature exports now preserve the schema.org mappings.

**Comment by pmackay** [comment]
Closing as schema.org mappings no longer a priority.
