### ISSUE TITLE
Create local development environment

### ISSUE THREAD

**Issue by sheldonrampton** [civic-commons/opencivic#9]
Paul, I've added the cat_lover theme directly to the apps_catalog git repository so we are no longer keeping it in  separate git repository. To work on the apps_catalog theming, therefore, I would like you to follow the approach to committing changes that is documented as "Aaron's alternative approach" in this Google doc:

https://docs.google.com/a/nuams.co/document/d/1Eucocy6HCeBKzNpxu7cYvlazqi_wUcc7TnRSpOaaF58/edit#

To build the full codebase on your local, you will use this drush make command:

drush make distro.make ../full_codebase --no-gitinfofile --working-copy

The apps catalog (including the SASS file you will use to make any CSS changes) will therefore be located at full_codebase/profiles/apps_catalog

To get your local copy of the website working fully, you will need to enable a features module named "AppCat misc" after the installation profile has completed. That feature enables all of the others that need to be enabled.

Please follow these instructions to create a local copy of the distro on your local computer and then do a test git commit to the theme and push it to the repository so we can confirm that the workflow for making changes is working. Then I'll want you to start working on ticket #10, which will involve theming the detail page for the Application content type.

**Comment by fusionx1** [comment]
im trying push my changes but it says "refusing to pull with rebase: your working tree is not up-to-date"

**Comment by acouch** [comment]
try "git pull --rebase" then "git push". does that work?

**Comment by acouch** [comment]
Looks like this also might be relevant: https://mail.gnome.org/archives/gnome-i18n/2009-April/msg00288.html

**Comment by acouch** [comment]
I might copy your changes before playing around too much.

**Comment by fusionx1** [comment]
still not working 
heres some short logs when git pull --rebase
themes/cat_lover/templates/views-view-fields--at-a-glance--block.tpl.php: needs update
themes/cat_lover/templates/views-view-fields--at-a-glance-application---block.tpl.php: needs update
themes/cat_lover/templates/views-view-fields--taxonomy-term-listing.tpl.php: needs update
themes/cat_lover/templates/views-view-rss.tpl.php: needs update
themes/cat_lover/templates/zone.tpl.php: needs update
refusing to pull with rebase: your working tree is not up-to-date
vagrant@lucid32:/var/www/apps_catalog/profiles/apps_catalog/modules$

**Comment by fusionx1** [comment]
at last i managed to make it work by copying the original .git/config and changed the url to git instead http
